-- Create benefits table for simple keywords
CREATE TABLE IF NOT EXISTS benefits (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create booster_benefits mapping table
CREATE TABLE IF NOT EXISTS booster_benefits (
  id SERIAL PRIMARY KEY,
  booster_id UUID REFERENCES boosters(id),
  benefit_id INTEGER REFERENCES benefits(id),
  UNIQUE(booster_id, benefit_id)
);

-- Insert comprehensive benefits list
INSERT INTO benefits (name, active) VALUES
('Acne Treatment', true),
('Anti-Acne', true),
('Anti-Aging', true),
('Anti-Bacterial', true),
('Anti-Cellulite', true),
('Anti-Dandruff', true),
('Anti-Frizz', true),
('Anti-Hair Loss', true),
('Anti-Inflammation', true),
('Anti-Oxidation', true),
('Anti-Redness', true),
('Anti-Rosacea', true),
('Anti-aging', true),
('Antioxidant', true),
('Balance Microbiome', true),
('Barrier Repair', true),
('Barrier Strengthening', true),
('Barrier Support', true),
('Blue Light Protection', true),
('Body Slimming', true),
('Body Toning', true),
('Breast Volume Enlargement', true),
('Brightening', true),
('Cell Renewal', true),
('Cellulite Reduction', true),
('Circulation', true),
('Collagen Boost', true),
('Color Protection', true),
('Dark Circle Reduction', true),
('Deep Hydration', true),
('Drainage', true),
('Draining Effect', true),
('Elasticity', true),
('Enhance microcirculation', true),
('Even out Skin Tone', true),
('Exfoliation', true),
('Ezcema Soothing', true),
('Facial Lifting', true),
('Fight Sagging', true),
('Firming', true),
('Hair Protection', true),
('Hydrating', true),
('Hydration', true),
('Increase Hair Density', true),
('Moisture Retention', true),
('Muscular Relaxation Effect', true),
('Odor Reduction', true),
('Oil Control', true),
('Plumping', true),
('Plumping and Filling Effects', true),
('Prevent TEWL', true),
('Prevents White Hair Formation', true),
('Psorasis Soothing', true),
('Puffiness Reduction', true),
('Radiance', true),
('Reduce Dark Circles', true),
('Reduce Fine Lines', true),
('Reduce Irritation', true),
('Reduce Itchiness', true),
('Reduce Muscle Pain', true),
('Reduce Puffiness', true),
('Reduce Stretch mark', true),
('Reduces Dark Spots', true),
('Reduces PIH', true),
('Rosacea Care', true),
('Scalp Nourishment', true),
('Skin Barrier Protection', true),
('Skin Barrier Repair', true),
('Smoothing', true),
('Stimulate Hair Growth', true),
('Texture Improvement', true),
('Tone Evening', true),
('Water Channeling', true),
('Wound Healing', true),
('Wrinkle Reduction', true)
ON CONFLICT (name) DO NOTHING;